name: Build Next.js Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      # Чекаут кода
      - uses: actions/checkout@v4

      # Настройка Node.js (нужна для совместимости с alpine)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Логин в GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Метаданные Docker
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/remna-mini-bot
          flavor: latest=true
          tags: |
            type=sha
            type=raw,value=${{ github.ref_name }}
            type=ref,event=tag

      # Сборка и пуш
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
